#include <iostream>

int main() {
    int suma = 3 + 3;
    std::cout<< "la suma es: "<<suma<<std::endl;
    
    return 0;
}
//suma

#include <iostream>

int main() {
    int num, num2;
    std::cout<<"introdusca un numero: "<<std::endl;
    std::cin>>num;
    std::cout<<"introdusca un numero: "<<std::endl;
    std::cin>>num2;
    int resta = num - num2;
    std::cout<< "la resta es: "<<resta<<std::endl;
    
    return 0;
}
//resta

include <iostream>

int main() {
    int num, num2;
    std::cout<<"introdusca un numero: "<<std::endl;
    std::cin>>num;
    std::cout<<"introdusca un numero: "<<std::endl;
    std::cin>>num2;
    int producto = num * num2;
    std::cout<< "la multiplicacion es: "<<producto<<std::endl;
    
    return 0;
}
//multiplicacion

#include <iostream>

int main() {
    int num, num2;
    std::cout<<"introdusca un numero que no sea 0: "<<std::endl;
    std::cin>>num;
    std::cout<<"introdusca un numero que no sea 0: "<<std::endl;
    std::cin>>num2;
    int division = num / num2;
    std::cout<< "la division es: "<<division<<std::endl;
    
    return 0;
}
//division

#include <iostream>

int main() {
    int num, num2;
    std::cout<<"introdusca un numero que no sea 0: "<<std::endl;
    std::cin>>num;
    std::cout<<"introdusca un numero que no sea 0: "<<std::endl;
    std::cin>>num2;
    int modulo = num % num2;
    std::cout<< "el residuo es: "<<modulo<<std::endl;
    
    return 0;
}
//modulo

#include <iostream>

int main() {
    int num, num2, num3;
    std::cout<<"introdusca un numero que no sea 0: "<<std::endl;
    std::cin>>num;
    std::cout<<"introdusca un numero que no sea 0: "<<std::endl;
    std::cin>>num2;
    std::cout<<"introdusca un numero que no sea 0: "<<std::endl;
    std::cin>>num3;
    int promedio = (num + num2 + num3) / 3;
    std::cout<< "el promedio es: "<<promedio<<std::endl;
    
    return 0;
}
//promedio

#include <iostream>

int main() {
    int num, num2;
    std::cout<<"introdusca la base: "<<std::endl;
    std::cin>>num;
    std::cout<<"introdusca la altura: "<<std::endl;
    std::cin>>num2;
    int area = num * num2;
    std::cout<< "el area del rectangulo es: "<<area<<std::endl;
    
    return 0;
}
//area de rectangulo

#include <iostream>

int main() {
    int num, num2;
    std::cout<<"introdusca un numero que no sea 0: "<<std::endl;
    std::cin>>num;
    std::cout<<"introdusca un numero que no sea 0: "<<std::endl;
    std::cin>>num2;
    int suma = num + num2;
    std::cout<< "el la suma es: "<<suma<<std::endl;
    int
    comparacion = num == num2;
    std::cout<< "los numeros son iguales: "<<comparacion<<std::endl;
    
    return 0;
}
//comparacion

#include <iostream>

int main() {
    int num, num2;
    std::cout<<"introdusca un numero que no sea 0: "<<std::endl;
    std::cin>>num;
    std::cout<<"introdusca un numero que no sea 0: "<<std::endl;
    std::cin>>num2;
    int suma = num + num2;
    std::cout<< "el la suma es: "<<suma<<std::endl;
    int producto = suma * suma;
    std::cout<< "el producto de la suma es: "<<producto<<std::endl;
    
    return 0;
}
//producto de la suma